# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isg_ai.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='isg_ai.proto',
  package='isg_ai',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0cisg_ai.proto\x12\x06isg_ai\"\xb1\x01\n\x12ImageYoloBoxesPair\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x12\n\nimg_height\x18\x02 \x01(\x05\x12\x11\n\timg_width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x11\n\tbox_count\x18\x05 \x01(\x05\x12\r\n\x05\x62oxes\x18\x06 \x01(\x0c\x12\x10\n\x08img_type\x18\x07 \x01(\t\x12\x10\n\x08\x62ox_type\x18\x08 \x01(\t\x12\r\n\x05label\x18\t \x01(\x05'
)




_IMAGEYOLOBOXESPAIR = _descriptor.Descriptor(
  name='ImageYoloBoxesPair',
  full_name='isg_ai.ImageYoloBoxesPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='isg_ai.ImageYoloBoxesPair.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_height', full_name='isg_ai.ImageYoloBoxesPair.img_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_width', full_name='isg_ai.ImageYoloBoxesPair.img_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='isg_ai.ImageYoloBoxesPair.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_count', full_name='isg_ai.ImageYoloBoxesPair.box_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='isg_ai.ImageYoloBoxesPair.boxes', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_type', full_name='isg_ai.ImageYoloBoxesPair.img_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_type', full_name='isg_ai.ImageYoloBoxesPair.box_type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='isg_ai.ImageYoloBoxesPair.label', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=202,
)

DESCRIPTOR.message_types_by_name['ImageYoloBoxesPair'] = _IMAGEYOLOBOXESPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageYoloBoxesPair = _reflection.GeneratedProtocolMessageType('ImageYoloBoxesPair', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEYOLOBOXESPAIR,
  '__module__' : 'isg_ai_pb2'
  # @@protoc_insertion_point(class_scope:isg_ai.ImageYoloBoxesPair)
  })
_sym_db.RegisterMessage(ImageYoloBoxesPair)


# @@protoc_insertion_point(module_scope)
